# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odczyty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odczytu', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('wilgotnosc', models.FloatField()),
                ('cisnienie', models.FloatField()),
            ],
            options={
                'verbose_name': 'Odczyt',
                'verbose_name_plural': 'Odczyty',
            },
        ),
        migrations.CreateModel(
            name='Odczyty_Algorytm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odczytu', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('wilgotnosc', models.FloatField()),
                ('cisnienie', models.FloatField()),
            ],
            options={
                'verbose_name': 'Odczyt stworozny przez algorytm',
                'verbose_name_plural': 'Odczyty stworzone przez algorytm',
            },
        ),
    ]
