# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacjapogodowa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odczyty_50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odczytu', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('wilgotnosc', models.FloatField()),
                ('cisnienie', models.FloatField()),
            ],
            options={
                'verbose_name': 'Odczyt stworozny przez algorytmy dla 50 do przodu',
                'verbose_name_plural': 'Odczyty stworzone przez algorytmy dla 50 do przodu',
            },
        ),
        migrations.RenameModel(
            old_name='Odczyty_Algorytm',
            new_name='Odczyty_10',
        ),
        migrations.AlterModelOptions(
            name='odczyty_10',
            options={'verbose_name': 'Odczyt stworozny przez algorytmy dla 10 do przodu', 'verbose_name_plural': 'Odczyty stworzone przez algorytmy dla 10 do przodu'},
        ),
    ]
