# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stacjapogodowa', '0002_odczyty_algorytm'),
    ]

    operations = [
        migrations.AddField(
            model_name='odczyty',
            name='kierunek_wiatru',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odczyty_algorytm',
            name='kierunek_wiatru',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
