# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacjapogodowa', '0003_auto_20171101_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odczyty',
        ),
        migrations.DeleteModel(
            name='Odczyty_Algorytm',
        ),
    ]
