# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stacjapogodowa', '0004_auto_20171102_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odczyty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odczytu', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('wilgotnosc', models.FloatField()),
                ('cisnienie', models.FloatField()),
                ('kierunek_wiatru', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Odczyty_Algorytm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odczytu', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('wilgotnosc', models.FloatField()),
                ('cisnienie', models.FloatField()),
                ('kierunek_wiatru', models.CharField(max_length=3)),
            ],
        ),
    ]
