# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacjapogodowa', '0005_odczyty_odczyty_algorytm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odczyty_algorytm',
            options={'verbose_name': 'My Book', 'verbose_name_plural': 'My Books'},
        ),
    ]
