# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacjapogodowa', '0006_auto_20171102_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odczyty',
            options={'verbose_name': 'Odczyt', 'verbose_name_plural': 'Odczyty'},
        ),
        migrations.AlterModelOptions(
            name='odczyty_algorytm',
            options={'verbose_name': 'Odczyt stworozny przez algorytm', 'verbose_name_plural': 'Odczyty stworzone przez algorytm'},
        ),
    ]
