# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacjapogodowa', '0007_auto_20171102_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odczyty',
            name='kierunek_wiatru',
        ),
        migrations.RemoveField(
            model_name='odczyty_algorytm',
            name='kierunek_wiatru',
        ),
    ]
